http:
  routers:
    test-router:
      rule: HostRegexp(`.*`)
      service: test-service
      entryPoints:
        - web
      middlewares:
        - swagger-merge-docs

  services:
    test-service:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:8080
          # - url: http:/service1:8081
          # - url: http:/service2:8082
  
  middlewares:
    swagger-merge-docs:
      plugin:
        path: /api/v1/docs/swagger.yaml
        refs:
          - path: http://service1:8081/swagger.yaml
          - path: http://service2:8082/swagger.yaml
