version: '3'
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - --api
      - --api.insecure=true
      - --log.level=DEBUG
      - --providers.file.directory=/config
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --experimental.localPlugins.swagger-merge-docs.moduleName=github.com/usalko/swagger-merge-docs-traefik-plugin
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./docker-config.yaml:/config/docker-config.yaml
      - ./:/plugins-local/src/github.com/usalko/swagger-merge-docs-traefik-plugin
    networks:
      - traefik

networks:
  traefik: {}