services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.debug=true
      # Включить Dashboard (только для разработки!)
      - --api.insecure=true
      # Включить автоматическое обнаружение Docker-сервисов
      - --providers.docker=true
      # Включить конфигурацию для передачи массива ссылок swagger-merge-docs plugin
      - --providers.file.directory=/config
      - --providers.file.watch=true
      # Логи для отладки
      - --log.level=DEBUG
      # Только явно разрешённые сервисы
      - --providers.docker.exposedbydefault=false
      # Основной HTTP
      - --entrypoints.web.address=:80
      # Development mode
      - --experimental.localPlugins.swagger-merge-docs.moduleName=github.com/usalko/swagger-merge-docs
      # Production mode
      # - --experimental.plugins.swagger-merge-docs.modulename=github.com/usalko/swagger-merge-docs
      # - --experimental.plugins.swagger-merge-docs.version=v0.1.0
    ports:
      - "8080:80"    # Balancer port
      - "8090:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/plugins-local/src/github.com/usalko/swagger-merge-docs
      - ./swagger-merge-docs-config.yaml:/config/swagger-merge-docs-config.yaml

  service1:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    env_file:
      - .env
    volumes:
      - ./tests/8081.yaml:/home/static/swagger.yaml
      - ./tests/index.html:/home/static/index.html
      - ./tests/feature1.json:/home/static/api/v1/feature1/index.html
    ports:
      - "${HTTP_PORT1:-8081}:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feature1.rule=PathPrefix(`/api/v1/feature1`)"
      - "traefik.http.routers.feature1.entrypoints=web"

  service2:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    env_file:
      - .env
    volumes:
      - ./tests/8082.yaml:/home/static/swagger.yaml
      - ./tests/index.html:/home/static/index.html
      - ./tests/feature2.json:/home/static/api/v1/feature2/index.html
    ports:
      - "${HTTP_PORT2:-8082}:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feature2.rule=PathPrefix(`/api/v1/feature2`)"
      - "traefik.http.routers.feature2.entrypoints=web"

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs.rule=PathPrefix(`/api/v1/whoami`)"
      - "traefik.http.routers.docs.middlewares.swagger=swagger-merge-docs"
      - "traefik.http.middlewares.swagger.plugin.swagger-merge-docs.path=/api/v1/docs"
      - "traefik.http.middlewares.swagger.plugin.swagger-merge-docs.docs.path=http://service1:8081/swagger.yaml"
      - "traefik.http.middlewares.swagger.plugin.swagger-merge-docs.docs.path=http://service2:8082/swagger.yaml"
