http:
  routers:
    test-router:
      rule: PathPrefix(`/api/v1/docs`)
      service: test-service
      middlewares:
        - swagger

  services:
    test-service:
      loadBalancer:
        servers:
          - url: http://whoami
  
  middlewares:
    swagger:
      plugin:
        swagger-merge-docs:
          path: /api/v1/docs
          docs:
            - path: http://service1:3000/swagger.yaml
            - path: http://service2:3000/swagger.yaml
